version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432 #temp for export
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: database
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:5050"
    container_name: pgadmin
    depends_on:
      - db

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: fastapi
    networks:
      - default
    ports:
      - 8888:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:8080


  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-app
  #   volumes:
  #     - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - frontend

volumes:
  app-db-data:

networks:
  example1:
    name: default
  
